name: Deploy app to Fly.io

on:
  push:
    paths:
      - akavas-app/**
    branches:
      - main  # Specifies that this workflow runs on pushes to the main branch
      # - fun  # Specifies that this workflow runs on pushes to the fun branch # - fun  # Specifies that this workflow runs on pushes to the fun branch
      # - ci-cd  # uncomment to test workflow on ci-cd branch

jobs:
  build-and-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: akavas-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: chmod +x bin/lint && ./bin/lint

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' -H 'Content-type: application/json' --data '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","text":"‚ùå Lint check failed! Deployment stopped."}' https://slack.com/api/chat.postMessage

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: fly deploy
        run: flyctl deploy --remote-only -a akavas
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_APP }}
